### ISSUE TITLE
Comments about micrortps branch

### ISSUE THREAD

**Issue by edersondisouza** [eProsima/Firmware#1]
Hi,

As I couldn't find a way to comment directly on branch, I created this issue to ask some questions:

 - I didn't see any CRC to ensure that data passed through UART reliably: shouldn't we have that?
 - On receivers, `readFromUART`, the copy from `rx_buffer` to `ser_buffer` appears unnecessary, just pass buffer offset to `FastBuffer`
 - Data on `readFromUART` is deserialized into `sensor_combined_` which is serialized again on `write` on publisher - maybe a shortcut here to avoid this deserialization step? 
 - Minor nitpick: each `serializeX` method has a check like

```cpp
if ((resize() == 0) || free >= needed)
```

Why it tries to resize first, and then check if it has space? I mean, first the function call, then a simple check? Why not the other way round?

**Comment by edersondisouza** [comment]
Just to note, I managed to write a sample here that sends commands to the flight stack, so, the other way round current sample. Currently generated code needs a bit of work to get there, specially because there's no deserialize from CDR to uORB (not generated at least), but it wasn't hard to get it working =D

**Comment by vicentemonge** [comment]
Hi,

Comments about yours:

- **CRC**:<s> Of course, we should have an integrity check and it will be added in future versions.</s>

- **rx_buffer and ser_buffer unnecessary duplicity**: Yes, is possible to work only with one buffer. It's introduced for development reasons and will be erased in future versions too.

- **ADDED** <s>**deserialization for internal micro CDR serialization**: Now we don't have a write interface version for serialized data thus it's necessary to deserialize before write. We will consider add this functionality.</s>

- **AVOIDED** <s>**((resize() == 0) || free >= needed)**: The check is done inside resize function but at the end we have to know if we are capable to write in the buffer because the return value is not enough verbose.</s>

- We would like to see this example :smiley:

**Comment by vicentemonge** [comment]
This comments affects to old code.
